export const defaultTabs = [
  'Breads & Bakery',
  'Breakfast & Dairy',
  'Meats & Seafood',
  'Fruits & Vegetables',
];

export const defaultPopularProducts = [
  {
    id: 1,
    name: '100 Percent Apple Juice - 64 fl oz Bottle',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'bottle',
    accent: '#f59e0b',
    img: '/product3.png',
    href: '/features',
    category: 'Breakfast & Dairy',
  },
  {
    id: 2,
    name: 'Rising Crust Supreme Pizza',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'box',
    accent: '#22c55e',
    img: '/product2.png',
    href: '/features',
    category: 'Breads & Bakery',
  },
  {
    id: 3,
    name: 'Simply Orange Juice - 52 fl oz Bottle',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'bottle',
    accent: '#f97316',
    img: '/product1.png',
    href: '/features',
    category: 'Breakfast & Dairy',
  },
  {
    id: 4,
    name: 'California Pizza Kitchen Margherita Pizza',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'box',
    accent: '#facc15',
    img: '/product3.png',
    href: '/features',
    category: 'Breads & Bakery',
  },
  {
    id: 5,
    name: "Lay's Classic Potato Chips Party Size",
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'bag',
    accent: '#facc15',
    img: '/product2.png',
    href: '/features',
    category: 'Fruits & Vegetables',
  },
  {
    id: 6,
    name: 'Angel Soft Mega Rolls Toilet Paper',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'rolls',
    accent: '#0891b2',
    img: '/product1.png',
    href: '/features',
    category: 'Meats & Seafood',
  },

  {
    id: 7,
    name: '100 Percent Apple Juice - 64 fl oz Bottle',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'bottle',
    accent: '#f59e0b',
    img: '/product3.png',
    href: '/features',
    category: 'Breakfast & Dairy',
  },
  {
    id: 8,
    name: 'Rising Crust Supreme Pizza',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'box',
    accent: '#22c55e',
    img: '/product2.png',
    href: '/features',
    category: 'Breads & Bakery',
  },
  {
    id: 9,
    name: 'Simply Orange Juice - 52 fl oz Bottle',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'bottle',
    accent: '#f97316',
    img: '/product1.png',
    href: '/features',
    category: 'Breakfast & Dairy',
  },
  {
    id: 10,
    name: 'California Pizza Kitchen Margherita Pizza',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'box',
    accent: '#facc15',
    img: '/product3.png',
    href: '/features',
    category: 'Breads & Bakery',
  },
  {
    id: 11,
    name: "Lay's Classic Potato Chips Party Size",
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'bag',
    accent: '#facc15',
    img: '/product2.png',
    href: '/features',
    category: 'Fruits & Vegetables',
  },
  {
    id: 12,
    name: 'Angel Soft Mega Rolls Toilet Paper',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'rolls',
    accent: '#0891b2',
    img: '/product1.png',
    href: '/features',
    category: 'Meats & Seafood',
  },
  
  
];

export const defaultLatestProducts = [
  {
    id: "a",
    name: '100 Percent Apple Juice - 64 fl oz Bottle',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'bottle',
    accent: '#f59e0b',
    img: '/product2.png',
    href: '/features',
    category: 'Breakfast & Dairy',
  },
  {
    id: "b",
    name: 'Rising Crust Supreme Pizza',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'box',
    accent: '#22c55e',
    img: '/product3.png',
    href: '/features',
    category: 'Breads & Bakery',
  },
  {
    id: "c",
    name: 'Simply Orange Juice - 52 fl oz Bottle',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'bottle',
    accent: '#f97316',
    img: '/product1.png',
    href: '/features',
    category: 'Breakfast & Dairy',
  },
  {
    id: "d",
    name: 'California Pizza Kitchen Margherita Pizza',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'box',
    accent: '#facc15',
    img: '/product3.png',
    href: '/features',
    category: 'Breads & Bakery',
  },
  {
    id: "e",
    name: "Lay's Classic Potato Chips Party Size",
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'bag',
    accent: '#facc15',
    img: '/product1.png',
    href: '/features',
    category: 'Fruits & Vegetables',
  },
  {
    id: "f",
    name: 'Angel Soft Mega Rolls Toilet Paper',
    price: '$25.99',
    originalPrice: '$38.10',
    rating: 4,
    imageType: 'rolls',
    accent: '#0891b2',
    img: '/product2.png',
    href: '/features',
    category: 'Meats & Seafood',
  },
];